docapp/urls.py
from django.conf.urls import url
from docapp import views

urlpatterns = [
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    # Company urls
    url(r'^company/$', views.list_company, name='list_company'),
    url(r'^company/(?P<company_id>[0-9]+)/$', views.detail_company, name='detail_company'),
    url(r'^register/company/$', views.register_company, name='register_company'),
    url(r'^update/company/(?P<company_id>[0-9]+)/$', views.update_company, name='update_company'),
    url(r'^employs/company/(?P<company_id>[0-9])+/$', views.list_employ_company, name='list_employ_company'),

    # Employ urls
    url(r'^person/$', views.list_independent_employ, name='list_independent_employ'),
    url(r'^person/(?P<person_id>[0-9]+)/$', views.detail_employ, name='detail_employ'),
    url(r'^register/person/$', views.register_employ_without_company, name='register_employ_without_company'),
    url(r'^register/person/(?P<company_id>[0-9]+)/$', views.register_employ_from_company,
        name='register_employ_from_company'),
    url(r'^update/person/(?P<person_id>[0-9]+)/$', views.update_employ, name='update_employ'),

    # Particular urls
    url(r'^patient/$', views.list_simple_patient, name='list_simple_patient'),
    url(r'^patient/(?P<pk>[0-9]+)/$', views.detail_patient, name='detail_patient'),
    url(r'^register/patient/$', views.register_simple_patient, name='register_simple_patient'),
    url(r'^update/patient/(?P<pk>[0-9]+)/$', views.update_simple_patient, name='update_simple_patient'),

    # Consults urls
    url(r'^consult/$', views.make_consulta, name='make_consult'),
    url(r'^assign_consult/$', views.assign_consult, name='assign_consult'),
    url(r'^enable_consults/$', views.list_consults_enable, name='enable_consults'),
    url(r'^consults/$', views.list_consults, name='list_consults'),
    url(r'^own_consults/$', views.lab_own_consults, name='list_own_consults'),
    url(r'^end_consult/$', views.end_consult, name='end_consult'),
    url(r'^list_end_consult/$', views.list_end_consults, name='list_end_consults'),


    # Antecedent urls
    url(r'^antecedent/(?P<person_id>[0-9])/$', views.list_employ_antecedents, name='list_employ_antecedents'),
    url(r'^antecedent/detail/(?P<antecedent_id>[0-9]+)/$', views.detail_employ_antecedent,
        name='detail_employ_antecedent'),
    url(r'^register/antecedent/(?P<person_id>[0-9]+)/$', views.register_employ_antecedent,
        name='register_employ_antecedent'),
    url(r'^update/antecedent/(?P<antecedent_id>[0-9]+)/$', views.update_employ_antecedent,
        name='update_employ_antecedent'),

    # Examination urls
    url(r'^register/exam/(?P<person_id>[0-9]+)/$', views.register_employ_examination,
        name='register_employ_examination'),
    url(r'^examination/$', views.list_examination, name='list_examination'),
    url(r'^examination/(?P<exam_id>[0-9]+)/$', views.detail_examination, name='detail_examination'),
    url(r'^take/examination/(?P<exam_id>[0-9]+)/$', views.take_a_exam, name='doctor_take_a_exam'),
    url(r'^my/examinations/$', views.own_examinations, name='doctor_own_examinations'),
    url(r'^end/examination/(?P<exam_id>[0-9]+)/$', views.doctor_end_exam, name='doctor_end_exam'),
    url(r'^end/examinations/$', views.end_examinations, name='doctor_end_examinations'),


    # Registro de examanes
    url(r'^register/(?P<exam_id>[0-9]+)/occupational/$', views.register_occupational, name='register_occupational'),
    url(r'^register/(?P<exam_id>[0-9]+)/audiology/$', views.register_audiology, name='register_audiology'),
    url(r'^register/(?P<exam_id>[0-9]+)/visiometry/$', views.register_visiometry, name='register_visiometry'),
    url(r'^register/(?P<exam_id>[0-9]+)/altura/$', views.register_altura, name='register_altura'),

    # Update exams
    url(r'^occupational/(?P<pk>[0-9]+)/$', views.update_ocupacional, name='update_ocupacional'),
    url(r'^audiology/(?P<pk>[0-9]+)/$', views.update_audiologia, name='update_audiologia'),
    url(r'^visiometry/(?P<pk>[0-9]+)/$', views.update_visiometria, name='update_visiometria'),
    url(r'^altura/(?P<pk>[0-9]+)/$', views.update_altura, name='update_altura'),
    url(r'^simple_exam/(?P<pk>[0-9]+)/$', views.register_simple_exam, name='register_simple_exam'),

    # Lab urls
    url(r'^labs/$', views.list_lab, name='list_lab'),
    url(r'^lab/(?P<pk>[0-9]+)/admin/$', views.list_admin_lab, name='list_admin_lab'),
    url(r'^register/lab/$', views.register_lab, name='register_lab'),
    url(r'^update/lab/(?P<lab_id>[0-9])/$', views.update_lab, name='update_lab'),
    url(r'^deactivate/lab/(?P<lab_id>[0-9])/$', views.deactivate_lab, name='deactivate_lab'),
    url(r'^register/lab/(?P<lab_id>[0-9]+)/admin/$', views.register_lab_admin, name='register_lab_admin'),
    url(r'^update/lab/admin/(?P<pk>[0-9]+)/$', views.update_lab_admin, name='update_lab_admin'),
    url(r'^delete/lab/admin/(?P<pk>[0-9]+)/$', views.deactivate_lab_admin, name='deactivate_lab_admin'),
    url(r'^lab/admin/(?P<pk>[0-9]+)/$', views.detail_lab_admin, name='detail_lab_admin'),
    url('^laboratory/(?P<lab_id>[0-9]+)/$', views.detail_laboratory, name='detail_laboratory'),

    # Other
    url('^filter/$', views.person_filter, name='person_filter')
]

docproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url('^grappelli/', include('grappelli.urls')),  # grappelli URLS
    url(r'^admin/', admin.site.urls),
    url(r'', include('docapp.urls', namespace='docapp')),
    url(r'', include('accounts.urls', namespace='accounts')),
    url(r'^labapp/', include('labapp.urls', namespace='labapp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labapp/urls.py
from django.conf.urls import url
from labapp import views

urlpatterns = [
    url('^register/personal/$', views.register_personal, name='register_personal'),
    url('^list/examinations/$', views.list_examination_todo, name='list_examination_todo'),
    url('^my/examinations/$', views.lab_own_examinations, name='lab_own_examinations'),
    url('^take/examination/(?P<exam_id>[0-9]+)/$', views.lab_take_a_exam, name='lab_take_a_exam'),
    url('^register/result/(?P<pk>[0-9]+)/$', views.register_lab_exam_result, name='register_lab_exam_result'),
    url('^update/results/(?P<pk>[0-9]+)/$', views.update_lab_exam_result, name='update_lab_exam_result'),
    url('^end/examination/(?P<exam_id>[0-9]+)/$', views.lab_end_exam, name='lab_end_exam'),
    url('^end/examinations/$', views.lab_end_examinations, name='lab_end_examinations')
]

docapp/forms/laboratory.py
from django import forms

from docapp.models import Laboratory, ExamenSangre, Examenes


class LabForm(forms.ModelForm):
    class Meta:
        model = Laboratory
        exclude = ('ultima_vez_modificado', 'tipo_examen', 'registrado_por',)

    def save(self, commit=True):
        instance = super(LabForm, self).save(commit=False)
        instance.tipo_examen = self.exam_type
        instance.registrado_por = self.create_by
        if commit:
            instance.save()
        return instance


blood_section = forms.inlineformset_factory(parent_model=Laboratory, model=ExamenSangre, extra=1, max_num=1,
                                            can_delete=False, fields='__all__')

exams_section = forms.inlineformset_factory(parent_model=Laboratory, model=Examenes, can_delete=True, fields='__all__')

docapp/views.py
from django.shortcuts import render, redirect, Http404
from django.contrib.auth.decorators import login_required
from django.views.generic import FormView, ListView, UpdateView, DetailView
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic.detail import SingleObjectMixin
from django.db import IntegrityError, transaction

from docapp.forms import CompanyForm, PersonForm, AntecedentForm, hazards_inlineformset, accidents_formset
from docapp.models import Company, Person, AntecedentJobs, Hazards, JobAccidents


# Permissions checker
class CheckerBase(UserPassesTestMixin):
    def handle_no_permission(self):
        return redirect('docapp:dashboard')

    def test_func(self):
        pass


class CheckReceptionist(CheckerBase):
    def test_func(self):
        return hasattr(self.request.user, 'reception_profile') or self.request.user.is_superuser


class CheckLaboratory(CheckerBase):
    def test_func(self):
        return hasattr(self.request.user, 'laboratory_profile') or self.request.user.is_superuser


class CheckDoctor(CheckerBase):
    def test_func(self):
        return hasattr(self.request.user, 'doctor_profile') or self.request.user.is_superuser


# Create your views here.
@login_required()
def dashboard(request):
    if request.user.is_staff and request.user.is_superuser:
        return redirect('admin:login')
    else:
        context = dict({
            'routes': ['Inicio'],
            'page_header': 'Dashboard Proof',
            'active': 'inicio',
            'exam_collapse': True,
        })
        return render(request, 'docapp/home.html', context)


class ListFilterView(ListView, SingleObjectMixin):
    """ Custom ListView to filter element only by pk_kwarg """
    model_to_filter = None
    context_object_2_name = None
    extra_context = None

    def get_object(self, queryset=None):
        """ Overwrite get_objet to only look with pk on Company model"""
        queryset = self.model_to_filter._default_manager.all()
        # Try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)

        # If none of those are defined, it's an error.
        if pk is None:
            raise AttributeError("Generic detail view %s must be called with "
                                 "either an object pk or a slug."
                                 % self.__class__.__name__)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(f"No {queryset.model._meta.verbose_name}s found matching the query")

        return obj

    def get_context_data(self, *, object_list=None, **kwargs):
        """ Get context data from MultiObjectMixin and ContentMixin to replace SingleObjectMixin method """
        # Add custom SingleObject
        if self.context_object_2_name is not None:
            kwargs[self.context_object_2_name] = self.get_object()
        else:
            kwargs['simple_object'] = self.get_object()
        # MultipleObjectMixin
        """Get the context for this view."""
        queryset = object_list if object_list is not None else self.object_list
        page_size = self.get_paginate_by(queryset)
        context_object_name = self.get_context_object_name(queryset)
        if page_size:
            paginator, page, queryset, is_paginated = self.paginate_queryset(queryset, page_size)
            context = {
                'paginator': paginator,
                'page_obj': page,
                'is_paginated': is_paginated,
                'object_list': queryset
            }
        else:
            context = {
                'paginator': None,
                'page_obj': None,
                'is_paginated': False,
                'object_list': queryset
            }
        if context_object_name is not None:
            context[context_object_name] = queryset

        context.update(kwargs)
        kwargs.update(context)  # Update kwargs with context information
        # ContentMixin section
        if 'view' not in kwargs:
            kwargs['view'] = self
        if self.extra_context:
            kwargs.update(self.extra_context)
        return kwargs


class FormViewPutExtra(FormView, SingleObjectMixin):
    model_to_filter = None
    context_object_2_name = 'parent_object'
    extra_context = None

    def get_object(self, queryset=None):
        """ Overwrite get_objet to get model_to_filter instance instead model instance """
        # get_objet to only look with pk on model_to_filter """
        queryset = self.model_to_filter._default_manager.all()
        # Try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)

        # If none of those are defined, it's an error.
        if pk is None:
            raise AttributeError("Generic detail view %s must be called with "
                                 "either an object pk or a slug."
                                 % self.__class__.__name__)

        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(f"No {queryset.model._meta.verbose_name}s found matching the query")

        return obj

    def get_context_data(self, **kwargs):
        """ Combine method from FormMixin and ContextMixin to manage correctly model """
        if self.context_object_2_name is not None:
            kwargs[self.context_object_2_name] = self.get_object()

        if 'form' not in kwargs:
            kwargs['form'] = self.get_form()
        if 'view' not in kwargs:
            kwargs['view'] = self
        if self.extra_context:
            kwargs.update(self.extra_context)

        return kwargs


class AntecedentPostManager(object):
    def post(self, request, *args, **kwargs):
        """ Overwrite post method to manage formsets """
        # Validate formsets
        hazard_formset = hazards_inlineformset(self.request.POST)
        accident_formset = accidents_formset(self.request.POST)

        if not hazard_formset.is_valid():
            messages.error(self.request, message="Error, Riesgos mal ingresados.")

        if not accident_formset.is_valid():
            messages.error(self.request, message="Error, Accidentes mal ingresados")

        if not hazard_formset.is_valid() or not accident_formset.is_valid():
            # Update formsets information (append errors and data)
            self.extra_context = {'accident_formset': accidents_formset,
                             'hazard_section': hazards_inlineformset}

            return self.form_invalid(form=self.get_form())

        antecedent_work = None
        if hasattr(self, '_custom_save'):
            """ Used only on Register Case """
            antecedent_work = self._custom_save(form=self.get_form())
            if not antecedent_work:
                # Update formsets information (append errors and data)
                self.extra_context = {'accident_formset': accidents_formset,
                                      'hazard_section': hazards_inlineformset}
                return self.form_invalid(form=self.get_form())
        
        response = super(AntecedentPostManager, self).post(request, *args, **kwargs)
        if antecedent_work is None:
            antecedent_work = self.object  # Is update process
        """ Managing formsets """
        # Get Hazard formset
        hazards = []
        for hazard in hazard_formset:
            data = {
                'fisico': hazard.cleaned_data.get('fisico'),
                'quimico': hazard.cleaned_data.get('quimico'),
                'mecanico': hazard.cleaned_data.get('mecanico'),
                'ergonomico': hazard.cleaned_data.get('ergonomico'),
                'electrico': hazard.cleaned_data.get('electrico'),
                'psicologico': hazard.cleaned_data.get('psicologico'),
                'work': antecedent_work,
                'locativo': hazard.cleaned_data.get('locativo')
            }
            hazards.append(Hazards(**data))

        try:
            with transaction.atomic():
                Hazards.objects.filter(work=antecedent_work).delete()
                Hazards.objects.bulk_create(hazards)
        except IntegrityError:
            messages.error(self.request, message="Error to save riesgos")

        # Accident formset
        accidents = []
        for accident in accident_formset:
            data = {
                'secuelas': accident.cleaned_data.get('secuelas'),
                'tipo': accident.cleaned_data.get('tipo'),
                'atendido': accident.cleaned_data.get('atendido'),
                'calificado': accident.cleaned_data.get('calificado'),
                'fecha': accident.cleaned_data.get('fecha'),
                'description': accident.cleaned_data.get('description'),
                'work': antecedent_work,
                'create_by': self.request.user.reception_profile
            }
            accidents.append(JobAccidents(**data))

        try:
            with transaction.atomic():
                JobAccidents.objects.filter(work=antecedent_work).delete()
                JobAccidents.objects.bulk_create(accidents)
        except IntegrityError:
            messages.error(self.request, message='Error to save accidents')

        return response


# List Views
class CompanyList(CheckReceptionist, LoginRequiredMixin, ListView):
    context_object_name = 'company_list'
    model = Company
    template_name = 'docapp/lists/company_list.html'


company_list = CompanyList.as_view()


class PersonList(CheckReceptionist, LoginRequiredMixin, ListView):
    context_object_name = 'person_list'
    model = Person

templates/docapp/details/antecedent.html
<div class="panel-body">
    <!-- Title -->
    <div class="row">
        <div class="col-sm-12 text-center">
            {% if request.user.doctor_profile %}
                <span class="pull-right">
                                <a href="{% url 'docapp:update_employ_antecedent' antecedent_id=antecedent.id %}">
                                                <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                                        data-placement="left" title="" data-original-title="Editar">
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </button>
                                            </a>
                            </span>
            {% endif %}
            <h1>Antecedentes de {{ antecedent.persona }}</h1>
            <small style="color: gainsboro">Registrado por: {{ antecedent.registrado_por.user_id.username }}</small>
        </div>
    </div>
    <hr>
    <!-- Information -->
    <div class="row">
        <div class="col-sm-12 text-left">
            <p><b>Empresa donde laboro:</b> {{ antecedent.nombre_empresa }}</p>
            <p><b>Cargo que tuvo:</b> {{ antecedent.ocupacion }}</p>
            <p><b>Tiempo de duracion:</b> {{ antecedent.tiempo }}</p>
            <p><b>Uso EPP:</b> {{ antecedent.uso_epp }}</p>
            <p><b>Numero de riesgos:</b> {{ antecedent.riesgos.get_number_hazard }}</p>
            <p><b>Riesgos:</b> {{ antecedent.riesgos.get_label_hazards }} </p>
            <p><b>Registrado por:</b> {{ antecedent.registrado_por.user_id.username }}</p>
            <p><b>Ultima vez modificado:</b> {{ antecedent.ultima_vez_modificado }}</p>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-sm-12">
            {% for accident in antecedent.accidentes.all %}
                <h4>Accidente #{{ forloop.counter }}</h4>
                <hr>
                <p><b>Tipo:</b> {{ accident.tipo }}</p>
                <p><b>Secuelas:</b> {{ accident.secuelas }}</p>
                <p><b>Atendido:</b> {{ accident.atendido }}</p>
                <p><b>Calificado:</b> {{ accident.calificado }}</p>
                <p><b>Fecha:</b> {{ accident.fecha }}</p>
                <p><b>Descripcion:</b> {{ accident.descripcion }}</p>
                <hr>
            {% empty %}
                <h2>No se registran accidentes</h2>
            {% endfor %}
        </div>
    </div>
</div>

templates/docapp/details/company.html
<div class="panel-body">
    <div class="row">
        <div class="col-sm-12 text-center">
            {% if request.user.reception_profile %}
                <span class="pull-right">
                            <a href="{% url 'docapp:update_company' company_id=company.id %}">
                                                <button class="btn btn-warning btn-xs" data-toggle="tooltip"
                                                        data-placement="left" title="" data-original-title="Editar">
                                                    <i class="fa fa-edit" aria-hidden="true"></i>
                                                </button>
                                            </a>
                            </span>
            {% endif %}
            <h1>{{ company.nombre|escape }}</h1>
            <address>
                <abbr title="NIT">{{ company.nit }}</abbr><br>
                <abbr title="Dirección">{{ company.direccion }}</abbr><br>
                <abbr title="Telefono"> {{ company.telefono }}</abbr><br>
                <abbr title="Celular">{{ company.celular }}</abbr><br>
                <a href="mailto:{{ company.correo_contacto }}">{{ company.correo_contacto }}</a>
            </address>
            <address>
                <p><b>Ultima vez modificado: </b> {{ company.ultima_vez_modificado }}</p>
            </address>
            <small style="color: gainsboro">Registrado por: {{ company.registrado_por.user }}</small>
        </div>
    </div>
    <hr>
    <h2>Empleados registrados</h2>
    <div class="table-responsive m-b-20">
        {% if company.empleados.all %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Identificacion</th>
                    <th>Nombre</th>
                    <th>Apellido</th>
                    <th>Telefono</th>
                    <th>Celular</th>
                    <th>Sexo</th>
                </tr>
                </thead>

                <tbody>
                {% for person in company.empleados.all %}
                    <tr>
                        <td>{{ person.identificacion }}</td>
                        <td>{{ person.nombres }}</td>
                        <td>{{ person.apellidos }}</td>
                        <td>{{ person.telefono }}</td>
                        <td>{{ person.celular }}</td>
                        <td>{{ person.sexo }}</td>
                    </tr>
                    {% if forloop.counter == 5 %}
                        {{ break }}
                    {% endif %}
                {% endfor %}
                </tbody>
            </table>
            <hr>
            <a class="btn btn-success pull-right"
               href="{% url 'docapp:list_employ_company' company_id=company.id %}"><i
                    class="fa fa-plus"></i>
                Ver más
            </a>
        {% else %}
            <h2>No se encuentran empleados registrados</h2>
        {% endif %}
    </div>
</div>

templates/docapp/details/examination.html
<div class="row">
    <div class="col-sm-12">
        <h2>Paciente: {{ exam.paciente_id }}</h2>
        <p><b>Proceso:</b> {{ exam.id }}</p>
        <p><b>Identificacion: </b>{{ exam.paciente_id.identificacion }}</p>
        <p><b>Tipo de examinacion:</b> {{ exam.tipo }} </p>
        {% if request.user.reception_profile %}
            <p><b>Doctor:</b> {% if exam.manejador_por %} {{ exam.manejador_por.user_id }} {% else %} No
                asignado {% endif %}</p>
            {% if exam.examenes_laboratorios.all %}
                {% with p_lab=exam.examenes_laboratorios.all.0 %}
                    <p><b>Laboratorio:</b> {{ p_lab.laboratorio_id }}</p>
                    <p><b>Personal de laboratorio:</b>
                        {% if p_lab.manejado_por %}{{ p_lab.manejado_por }}{% else %} No asignado {% endif %}</p>
                {% endwith %}
            {% else %}
                <p><b>No presenta examenes de laboratorio</b></p>
            {% endif %}
        {% endif %}
        <small><span class="label label-warning-outline">No registrado</span> <span
                class="label label-success-outline">Registrado</span></small>
    </div>
</div>
{% if request.user.doctor_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <div class="progress progress-lg" style="max-width: none">
                <div {% if exam.get_doctor_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_doctor_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="{{ exam.get_doctor_process }}" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_doctor_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
    {# Common Exams #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes comunes a realizar</h3>
            <ul>
                {% if exam.do_exam_altura %}
                    <li>
                        <span class="label {% if exam.altura %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_altura' exam_id=exam.id %}">Registrar Resultados Altura</a>
                        </span>
                    </li>
                {% endif %}
                {% if exam.do_exam_audiologia %}

                    <li>
                        <span class="label {% if exam.audiologia %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_audiology' exam_id=exam.id %}">Registrar Resultados Audiologia</a>
                        </span>
                    </li>
                {% endif %}
                {% if exam.do_exam_visiometria %}

                    <li>
                        <span class="label {% if exam.visiometria %} label-success-outline {% else %} label-warning-outline {% endif %}">
                            <a href="{% url 'docapp:register_visiometry' exam_id=exam.id %}">Registrar Resultados Visiometria</a>
                        </span>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
    {# Inter Exams #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes internos a realizar</h3>
            {% if exam.examenes_internos.all %}
                <ul>
                    {% for examen in exam.examenes_internos.all %}
                        <li class="m-t-20">
                        <span class="label {% if examen.resultados != '' %} label-success-outline {% else %} label-warning-outline {% endif %}">
                                <a href="{% url 'docapp:register_simple_exam' pk=examen.id %}">Registrar resultados
                                de {{ examen.nombre }}</a>
                        </span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
    {# Done process #}
    <div class="row">
        <div class="col-sm-12">
                <span class="pull-right">
                    <a href="{% url 'docapp:register_occupational' exam_id=exam.id %}">
                    <button class="btn btn-primary">Registrar Resumen del proceso <i
                            class="fa fa-drivers-license-o"></i></button></a>
                </span>
        </div>
    </div>
{% elif request.user.laboratory_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <div class="progress progress-lg" style="max-width: none">
                <div {% if exam.get_lab_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_lab_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="80" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_lab_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
    {# Examenes de laboratorio #}
    <div class="row">
        <div class="col-sm-12">
            <h3>Examenes de laboratorios a realizar</h3>
            {% if exam.examenes_laboratorios.all %}
                <ul>
                    {% for examen in exam.examenes_laboratorios.all %}
                        <li class="m-t-20">
                        <span class="label {% if examen.resultados.all %} label-success-outline {% else %} label-warning-outline {% endif %}">
                                <a href="{% url 'labapp:register_lab_exam_result' pk=examen.id %}">Registrar resultados
                                de {{ examen.nombre }}</a>
                        </span>
                        </li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
{% elif request.user.reception_profile %}
    <div class="row">
        <div class="col-sm-12"><h2>Porcentaje del proceso</h2></div>
        <div class="col-sm-12">
            <label for="doc_process">Doctor</label>
            <div class="progress progress-lg" id="doc_process" style="max-width: none">
                <div {% if exam.get_doctor_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_doctor_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="{{ exam.get_doctor_process }}" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_doctor_process }}% Realizado
                </div>
            </div>
        </div>
        <div class="col-sm-12">
            <label for="lab_process">Laboratorio</label>
            <div class="progress progress-lg" id="lab_process" style="max-width: none">
                <div {% if exam.get_lab_process > 0 %}
                    class="progress-bar progress-bar-striped active progress-bar-success"
                    style="width: {{ exam.get_lab_process }}%"
                {% else %}
                    class="progress-bar  progress-bar-striped active progress-bar-danger" style="width: 100%"
                {% endif %}
                    role="progressbar" aria-valuenow="80" aria-valuemin="0"
                    aria-valuemax="100">
                    {{ exam.get_lab_process }}% Realizado
                </div>
            </div>
        </div>
    </div>
{% endif %}